from . import bi_granjas_ubicaciones
from . import bi_parvadas
from . import bi_recepcion
from . import bi_distribucion
from . import bi_mortalidad
from . import bi_tolvas
from . import bi_empaque
from . import bi_alimento
from . import bi_produccion
from . import bi_parametros
from . import bi_peso_uniformidad
from . import dashboard